WebCIIPMaestrosERP/Controllers/MaeCursoLanzamientoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using WebCIIPMaestrosERP.Models;
using WebCIIPMaestrosERP.Seguridad;

namespace WebCIIPMaestrosERP.Controllers
{
    [Acceder]
    public class MaeCursoLanzamientoController : Controller
    {
        // GET: MaeCursoLanzamiento
        public ActionResult Index()
        {

            llenarCurso();
            LlenarTutor();
            llenarTipoCurso();

            ViewBag.lista = ListaCursos;
            ViewBag.listaTutor = ListaTutor;
            ViewBag.listaTipoCurso = ListaTipoCurso;


            List<MaeCursoLanzamientoCLS> ListaLanzamientos = null;

            using (var db = new DB_WebCIIPEntitiesERP())
            {
                ListaLanzamientos = (from lanzamiento in db.MAE_CURSOS_LANZAMIENTOS
                                     join cursos in db.MAE_CURSOS
                                     on lanzamiento.CUR_ID equals cursos.CUR_ID
                                     join tutores in db.MAE_TUTOR
                                     on lanzamiento.TUT_ID equals tutores.TUT_ID
                                     join tablas in db.MAE_TABLAS
                                     on lanzamiento.LAN_ACTIVO equals tablas.ID.ToString()
                                     where tablas.COD_TABLA == "ACT" 

                                     select new MaeCursoLanzamientoCLS
                                     {
                                         LAN_ID = lanzamiento.LAN_ID,
                                         CUR_ID = lanzamiento.CUR_ID,
                                         TUT_ID = lanzamiento.TUT_ID,
                                         LAN_ESTADO = tablas.DESCRIPCION,
                                         CUR_NOMBRE = cursos.CUR_NOMBRE,
                                         TUT_NOMBRES = tutores.TUT_NOMBRES+" "+tutores.TUT_APELLIDOS,
                                         LAN_FEC_CAPACITACION = (DateTime)lanzamiento.LAN_FEC_CAPACITACION
                                     }).ToList();
            }

            return View(ListaLanzamientos);
        }

        public ActionResult Filtro(string nombreLanzamiento)
        {

            List<MaeCursoLanzamientoCLS> listaLanzamientos = new List<MaeCursoLanzamientoCLS>();
            using (var db = new DB_WebCIIPEntitiesERP())
            {
                if (nombreLanzamiento == null)
                    listaLanzamientos = (from lanzamiento in db.MAE_CURSOS_LANZAMIENTOS
                                         join cursos in db.MAE_CURSOS
                                         on lanzamiento.CUR_ID equals cursos.CUR_ID
                                         join tutores in db.MAE_TUTOR
                                         on lanzamiento.TUT_ID equals tutores.TUT_ID
                                         join tablas in db.MAE_TABLAS
                                         on lanzamiento.LAN_ACTIVO equals tablas.ID.ToString()
                                         where tablas.COD_TABLA == "ACT"

                                         select new MaeCursoLanzamientoCLS
                                         {
                                             LAN_ID = lanzamiento.LAN_ID,
                                             CUR_ID = lanzamiento.CUR_ID,
                                             TUT_ID = lanzamiento.TUT_ID,
                                             CUR_NOMBRE = cursos.CUR_NOMBRE,
                                             LAN_ESTADO = tablas.DESCRIPCION,
                                             TUT_NOMBRES = tutores.TUT_NOMBRES + " " + tutores.TUT_APELLIDOS,
                                             LAN_FEC_CAPACITACION = (DateTime)lanzamiento.LAN_FEC_CAPACITACION
                                         }).ToList();
                else
                    listaLanzamientos = (from lanzamiento in db.MAE_CURSOS_LANZAMIENTOS
                                         join cursos in db.MAE_CURSOS
                                         on lanzamiento.CUR_ID equals cursos.CUR_ID
                                         join tutores in db.MAE_TUTOR
                                         on lanzamiento.TUT_ID equals tutores.TUT_ID
                                         join tablas in db.MAE_TABLAS
                                         on lanzamiento.LAN_ACTIVO equals tablas.ID.ToString()
                                         where tablas.COD_TABLA == "ACT" &&
                                                (cursos.CUR_NOMBRE.Contains(nombreLanzamiento)
                                                || tutores.TUT_NOMBRES.Contains(nombreLanzamiento)
                                                || tutores.TUT_APELLIDOS.Contains(nombreLanzamiento))
                                         select new MaeCursoLanzamientoCLS
                                         {
                                             LAN_ID = lanzamiento.LAN_ID,
                                             CUR_ID = lanzamiento.CUR_ID,
                                             TUT_ID = lanzamiento.TUT_ID,
                                             CUR_NOMBRE = cursos.CUR_NOMBRE,
                                             LAN_ESTADO = tablas.DESCRIPCION,
                                             TUT_NOMBRES = tutores.TUT_NOMBRES + " " + tutores.TUT_APELLIDOS,
                                             LAN_FEC_CAPACITACION = (DateTime)lanzamiento.LAN_FEC_CAPACITACION
                                         }).ToList();
            }
            return PartialView("_Index", listaLanzamientos);
        }

        public int ActivarDesactivar(int id, string estado)
        {
            int nregistrosAfectados = 0;
            try
            {
                using (var db = new DB_WebCIIPEntitiesERP())
                {
                    MAE_CURSOS_LANZAMIENTOS oMAE_CURSOS_LANZAMIENTOS = db.MAE_CURSOS_LANZAMIENTOS.Where(p => p.LAN_ID == id).First();
                    oMAE_CURSOS_LANZAMIENTOS.LAN_ACTIVO = estado;
                    nregistrosAfectados = db.SaveChanges();
                }

            }
            catch (Exception ex)
            {

                nregistrosAfectados = 0;
            }

            return nregistrosAfectados;
        }
        public string GuardarNuevoControladorParcial(MaeCursoLanzamientoCLS oMaeCursoLanzamientoCLS, int accion)
        {
            string rpta = "";
            int idLanzamiento = 0;
            //decimal idLanzamientoEncrip = 0;


                using (var db = new DB_WebCIIPEntitiesERP())

                {
                if (accion == -1)
                {
                    MAE_CURSOS_LANZAMIENTOS oMaeCursoLanzamiento = new MAE_CURSOS_LANZAMIENTOS();
                    oMaeCursoLanzamiento.CUR_ID = oMaeCursoLanzamientoCLS.CUR_ID;
                    oMaeCursoLanzamiento.TUT_ID = oMaeCursoLanzamientoCLS.TUT_ID;
                    oMaeCursoLanzamiento.LAN_ACTIVO = "1";
                    oMaeCursoLanzamiento.LAN_FEC_CAPACITACION = oMaeCursoLanzamientoCLS.LAN_FEC_CAPACITACION;
                    oMaeCursoLanzamiento.IND_TIPO_LAN = oMaeCursoLanzamientoCLS.IND_TIPO_LAN;
                    db.MAE_CURSOS_LANZAMIENTOS.Add(oMaeCursoLanzamiento);
                    rpta = db.SaveChanges().ToString();

                    //debemos recuperar el numero del id para encriptarlo
                    idLanzamiento = oMaeCursoLanzamiento.LAN_ID; // recuperar

                    //iniciamos la encriptacion

                    using (var transacction = new TransactionScope())
                    {

                        SHA256Managed sha = new SHA256Managed();
                        byte[] byteContra = Encoding.Default.GetBytes(idLanzamiento.ToString());
                        byte[] byteContraCifrado = sha.ComputeHash(byteContra);
                        string cadenaContraCifrada = BitConverter.ToString(byteContraCifrado).Replace("-", "");


                        MAE_CURSOS_LANZAMIENTOS oMAE_CURSOS_LANZAMIENTOS = db.MAE_CURSOS_LANZAMIENTOS.Where(p => p.LAN_ID == idLanzamiento).First();
                        oMAE_CURSOS_LANZAMIENTOS.LAN_ID_ENCRIPTADO = cadenaContraCifrada;
                        rpta = db.SaveChanges().ToString();
                        transacction.Complete();

                    }

                }
                else {

                    MAE_CURSOS_LANZAMIENTOS oMAE_CURSOS_LANZAMIENTOS = db.MAE_CURSOS_LANZAMIENTOS.Where(p => p.LAN_ID == accion).First();
                    oMAE_CURSOS_LANZAMIENTOS.CUR_ID = oMaeCursoLanzamientoCLS.CUR_ID;
                    oMAE_CURSOS_LANZAMIENTOS.TUT_ID = oMaeCursoLanzamientoCLS.TUT_ID;
                    oMAE_CURSOS_LANZAMIENTOS.IND_TIPO_LAN = oMaeCursoLanzamientoCLS.IND_TIPO_LAN;
                    oMAE_CURSOS_LANZAMIENTOS.LAN_FEC_CAPACITACION = oMaeCursoLanzamientoCLS.LAN_FEC_CAPACITACION;
                    rpta = db.SaveChanges().ToString();


                }


            }

            return rpta;

        }

        public JsonResult recuperarDatos(int IdLanzamiento)
        {

            MaeCursoLanzamientoCLS oMaeCursoLanzamientoCLS = new MaeCursoLanzamientoCLS();
            using (var db = new DB_WebCIIPEntitiesERP())
            {
                MAE_CURSOS_LANZAMIENTOS oMAE_CURSOS_LANZAMIENTOS = db.MAE_CURSOS_LANZAMIENTOS.Where(p => p.LAN_ID.Equals(IdLanzamiento)).First();

                oMaeCursoLanzamientoCLS.CUR_ID = oMAE_CURSOS_LANZAMIENTOS.CUR_ID;
                oMaeCursoLanzamientoCLS.TUT_ID = oMAE_CURSOS_LANZAMIENTOS.TUT_ID;
                oMaeCursoLanzamientoCLS.IND_TIPO_LAN = oMAE_CURSOS_LANZAMIENTOS.IND_TIPO_LAN;
                oMaeCursoLanzamientoCLS.LAN_FEC_CAPACITACIONCADENA = oMAE_CURSOS_LANZAMIENTOS.LAN_FEC_CAPACITACION!= null ?

WebCIIPMaestrosERP/Views/MaeCursoLanzamiento/Index.cshtml
@using WebCIIPMaestrosERP.Models;
@model List<MaeCursoLanzamientoCLS>

@{
    ViewBag.Title = "Index";
    List<SelectListItem> ListaCursos = (List<SelectListItem>)ViewBag.lista;
    List<SelectListItem> ListaTutor = (List<SelectListItem>)ViewBag.listaTutor;
    List<SelectListItem> ListaTipoCurso = (List<SelectListItem>)ViewBag.ListaTipoCurso;

}

<h2>Configurar Lanzamientos</h2>


<!-- Button trigger modal -->
<button type="button" onclick="Agregar()" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModalLanzamiento">
    Agregar
</button>



@using (Ajax.BeginForm("Filtro", "", new AjaxOptions
{
    HttpMethod = "POST",
    UpdateTargetId = "divRol",
    InsertionMode = InsertionMode.Replace
}, new { @id = "frmFiltro" }))
{
    @Html.Label("Buscar por")
    @Html.TextBox("nombreLanzamiento", null, new { @class = "form-control" })
    <div id="divRol">
        @Html.Partial("_Index", Model)
    </div>
}


<!-- Modal -->
<div class="modal fade" id="myModalLanzamiento" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Nuevo Lanzamiento</h4>
            </div>


            @using (Ajax.BeginForm("GuardarNuevoControladorParcial", "MaeCursoLanzamiento", null, new AjaxOptions
            {
                HttpMethod = "POST",
                OnSuccess = "Guardar",
                UpdateTargetId = "error"
            }))
            {

                @Html.Hidden("accion") //Para  saber si esta guardando o actualizando, -1 = insertar, -2 actualuzar


                <table>
                    <tr>
                        <td>
                            <div class="modal-body">
                                @Html.LabelFor(p => Model[0].CUR_ID)
                                @Html.DropDownList("CUR_ID", ListaCursos, new { @class = "form-control" })
                                @Html.ValidationMessage("CUR_ID", new { @class = "text-danger" })
                            </div>
                        </td>
                        <td>
                            <div class="modal-body">
                                @Html.LabelFor(p => Model[0].TUT_ID)
                                @Html.DropDownList("TUT_ID", ListaTutor, new { @class = "form-control" })
                                @Html.ValidationMessage("TUT_ID", new { @class = "text-danger" })
                            </div>
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <div class="modal-body">
                                @Html.LabelFor(p => Model[0].LAN_FEC_CAPACITACION)
                                <!--@@Html.Editor("LAN_FEC_CAPACITACION", null, new { htmlAttributes = new { @@class = "form-control", @@type = "datetime-local" } })-->
                                <input type="date" id="LAN_FEC_CAPACITACION" name="LAN_FEC_CAPACITACION"
                                       value="2018-07-22"
                                       min="2018-01-01" max="2018-12-31">

                                @Html.ValidationMessage("LAN_FEC_CAPACITACION", new { @class = "text-danger" })
                            </div>
                        </td>

                        <td>
                            <div class="modal-body">
                                @Html.LabelFor(p => Model[0].IND_TIPO_LAN)
                                @Html.DropDownList("IND_TIPO_LAN", ListaTipoCurso, new { @class = "form-control" })
                                @Html.ValidationMessage("IND_TIPO_LAN", new { @class = "text-danger" })
                            </div>
                        </td>

                    </tr>


                </table>

                <div class="modal-footer">
                    <button type="button" id="btnClose" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>


            }
        </div>
        <div class="text-danger" id="error"></div>
    </div>
</div>

<!-- Modal Eliminar -->
<div class="modal fade" id="ModalConfirmacion" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">

                <div class="alert alert-danger" role="alert"><h5 class="modal-title" id="exampleModalLabel">¿Desea desactivar el registro?</h5></div>

            </div>

            <div style="padding:1em">
                <button type="button" id="btnCerrarConfirmacion" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" onclick="ConfirmarActivarDescativar(2)" class="btn btn-danger">Aceptar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Activar -->
<div class="modal fade" id="ModalActivar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">

                <div class="alert alert-success" role="alert"><h5 class="modal-title" id="exampleModalLabel">¿Desea activar el registro?</h5></div>

            </div>

            <div style="padding:1em">
                <button type="button" id="btnCerrarConfirmacion" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" onclick="ConfirmarActivarDescativar(1)" class="btn btn-success">Aceptar</button>
            </div>
        </div>
    </div>
</div>


<script>



    var nombre = document.getElementById("nombreLanzamiento");
    nombre.onkeyup = function () {
        $("#frmFiltro").trigger("submit");
    }


    function ConfirmarActivarDescativar(estado) {
        var id = document.getElementById("accion").value;
        $.get("MaeCursoLanzamiento/ActivarDesactivar/?id=" + id + "&estado=" + estado, function (data) {

            if (data == 1) {
                alert("Se ejecuto correctamente");
                document.getElementById("btnCerrarConfirmacion").click();
                $("#frmFiltro").trigger("submit");
            } else {
                alert("Ocurrio un error");
            }

        })

    }


    function ActivarDesactivar(idLan) {
        document.getElementById("accion").value = idLan;
    }



    function limpiar() {
        var controles = document.getElementsByClassName("form-control");
        var ncontroles = controles.length;

        for (var i = 0; i < ncontroles; i++) {
            controles[i] = value = "";

        }


        document.getElementById("CUR_ID").value = "";
        document.getElementById("TUT_ID").value = "";
        //document.getElementById("LAN_FEC_CAPACITACION").value = "01/01/1900";




        document.getElementById("error").innerHTML = "";

    }

    function Agregar() {
        limpiar();
        document.getElementById("accion").value = -1;



    }

    function Guardar(resultado) {
        if (resultado == 1) {

            document.getElementById("btnClose").click();
            $("#frmFiltro").trigger("submit");
            alert("Se guardo correctamente");
        } else {
            alert("Ocurrio un error");
        }

    }

    function Editar(IdLanzamiento) {
        limpiar();

        document.getElementById("accion").value = IdLanzamiento;

        $.get("MaeCursoLanzamiento/recuperarDatos/?IdLanzamiento=" + IdLanzamiento, function (data) {
            document.getElementById("CUR_ID").value = data.CUR_ID;
            document.getElementById("TUT_ID").value = data.TUT_ID;
            document.getElementById("LAN_FEC_CAPACITACION").value = data.LAN_FEC_CAPACITACIONCADENA;
            document.getElementById("IND_TIPO_LAN").value = data.IND_TIPO_LAN;
            
            
        })

    }



</script>

WebCIIPMaestrosERP/Views/MaeCursoLanzamiento/_Index.cshtml
@using WebCIIPMaestrosERP.Models;
@model  List<MaeCursoLanzamientoCLS>




<table class="table table-bordered table-hover">
    <thead>

        <tr>
            <td width="5%">@Html.LabelFor(p => Model[0].LAN_ID)</td>
            <td width="20%">@Html.LabelFor(p => Model[0].CUR_NOMBRE)</td>
            <td width="20%">@Html.LabelFor(p => Model[0].TUT_NOMBRES)</td>
            <td width="20%">@Html.LabelFor(p => Model[0].LAN_FEC_CAPACITACION)</td>
            <td width="20%">@Html.LabelFor(p => Model[0].LAN_ESTADO)</td>
            <th width="20%">OPERACIONES</th>

        </tr>

    </thead>

    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@item.LAN_ID</td>
            <td>@item.CUR_NOMBRE</td>
            <td>@item.TUT_NOMBRES</td>
            <td>@item.LAN_FEC_CAPACITACION</td>
            <td>@item.LAN_ESTADO</td>
            <td>
                <button type="button" onclick="Editar(@item.LAN_ID)" class="btn btn-primary glyphicon glyphicon-edit" data-toggle="modal" data-target="#myModalLanzamiento">
                </button>

                <button type="button" onclick="ActivarDesactivar(@item.LAN_ID)" class="btn btn-danger glyphicon glyphicon-trash" data-toggle="modal" data-target="#ModalConfirmacion">
                </button>

                <button type="button" onclick="ActivarDesactivar(@item.LAN_ID)" class="btn btn-success glyphicon glyphicon-ok-circle" data-toggle="modal" data-target="#ModalActivar">
                </button>
            </td>
        </tr>
        }
    </tbody>

</table>