WebCIIPMaestrosERP/Models/SEG_CURSOS_USUARIOS_LINKS.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCIIPMaestrosERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEG_CURSOS_USUARIOS_LINKS
    {
        public int CUS_ID { get; set; }
        public int USU_ID { get; set; }
        public int CUR_ID { get; set; }
        public string USU_LINK { get; set; }
        public string USU_LINK_CORTO { get; set; }
        public string LNK_ACTIVO { get; set; }
    
        public virtual SEG_USUARIOS SEG_USUARIOS { get; set; }
        public virtual MAE_CURSOS MAE_CURSOS { get; set; }
    }
}

WebCIIPMaestrosERP/Controllers/SegCursosUsuariosLinksController.cs
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Transactions;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using WebCIIPMaestrosERP.Models;

namespace WebCIIPMaestrosERP.Controllers
{
    public class SegCursosUsuariosLinksController : Controller
    {


        List<SelectListItem> ListaUsuarios;
        private void llenarUsuarios()
        {
            using (var db = new DB_WebCIIPEntitiesERP())
            {

                ListaUsuarios = (from usuarios in db.SEG_USUARIOS
                               where usuarios.USU_ACTIVO == "1" && usuarios.ROL_ID == 1 // solo lista los usuarios de marketing o bots
                                 select new SelectListItem
                               {
                                   Text = usuarios.USU_NOMBRES+" "+ usuarios.USU_APELLIDO,
                                   Value = usuarios.USU_ID.ToString()

                               }).ToList();
            }

        }

        List<SelectListItem> ListaCursos;
        private void llenarCursos()
        {
            using (var db = new DB_WebCIIPEntitiesERP())
            {

                ListaCursos = (from cursos in db.MAE_CURSOS
                               where cursos.CUR_ACTIVO == "1" 
                               select new SelectListItem
                               {
                                   Text = cursos.CUR_NOMBRE,
                                   Value = cursos.CUR_ID.ToString()

                               }).ToList();
            }

        }


        public ActionResult VerLinks(SegCursoUsuarioLinksCLS oSegCursoUsuarioLinksCLS)
        {
            
            return View();
        }

        // GET: SegCursosUsuariosLinks
        public ActionResult Index(SegCursoUsuarioLinksCLS oSegCursoUsuarioLinksCLS)
        {
            llenarCursos();
            llenarUsuarios();

            ViewBag.ListaCursos = ListaCursos;
            ViewBag.ListaUsuarios = ListaUsuarios;

            List<SegCursoUsuarioLinksCLS> ListaCursoByUsuario = null;

            string nombreCurso = oSegCursoUsuarioLinksCLS.USU_NOMBRES;

            using (var db = new DB_WebCIIPEntitiesERP())
            {

                if (nombreCurso == null)
                {

                    ListaCursoByUsuario = (from CursosByUsuarios in db.SEG_CURSOS_USUARIOS_LINKS
                                           join cursos in db.MAE_CURSOS
                                            on CursosByUsuarios.CUR_ID equals cursos.CUR_ID
                                           join usuarios in db.SEG_USUARIOS
                                           on CursosByUsuarios.USU_ID equals usuarios.USU_ID
                                          
                                           orderby cursos.CUR_ID

                                           select new SegCursoUsuarioLinksCLS

                                           {
                                               CUS_ID = CursosByUsuarios.CUS_ID,
                                               CUR_ID = cursos.CUR_ID,
                                               CUR_NOMBRE = cursos.CUR_NOMBRE,
                                               CUR_DESCRIPCION = cursos.CUR_DESCRIPCION,
                                               USU_ID = usuarios.USU_ID,
                                               USU_NOMBRES = usuarios.USU_NOMBRES+" "+ usuarios.USU_APELLIDO,
                                               USU_LINK = CursosByUsuarios.USU_LINK,
                                               USU_LINK_CORTO = CursosByUsuarios.USU_LINK_CORTO
                                           }).ToList();

                }
                else {


                    ListaCursoByUsuario = (from CursosByUsuarios in db.SEG_CURSOS_USUARIOS_LINKS
                                           join cursos in db.MAE_CURSOS
                                            on CursosByUsuarios.CUR_ID equals cursos.CUR_ID
                                           join usuarios in db.SEG_USUARIOS
                                           on CursosByUsuarios.USU_ID equals usuarios.USU_ID
                                           where
                                               usuarios.USU_NOMBRES.Contains(nombreCurso)
                                           orderby cursos.CUR_ID

                                           select new SegCursoUsuarioLinksCLS

                                           {
                                               CUS_ID = CursosByUsuarios.CUS_ID,
                                               CUR_ID = cursos.CUR_ID,
                                               CUR_NOMBRE = cursos.CUR_NOMBRE,
                                               CUR_DESCRIPCION = cursos.CUR_DESCRIPCION,
                                               USU_ID = usuarios.USU_ID,
                                               USU_NOMBRES = usuarios.USU_NOMBRES + " " + usuarios.USU_APELLIDO,
                                               USU_LINK = CursosByUsuarios.USU_LINK,
                                               USU_LINK_CORTO = CursosByUsuarios.USU_LINK_CORTO
                                           }).ToList();

                }

            }
            return View(ListaCursoByUsuario);
        }


        public int ActivarDesactivar(int id, string estado)
        {
            int nregistrosAfectados = 0;
            try
            {
                using (var db = new DB_WebCIIPEntitiesERP())
                {
                    SEG_CURSOS_USUARIOS_LINKS oSEG_CURSOS_USUARIOS_LINKS = db.SEG_CURSOS_USUARIOS_LINKS.Where(p => p.CUS_ID == id).First();
                    oSEG_CURSOS_USUARIOS_LINKS.LNK_ACTIVO = estado;
                    nregistrosAfectados = db.SaveChanges();
                }

            }
            catch (Exception ex)
            {

                nregistrosAfectados = 0;
            }

            return nregistrosAfectados;
        }


        public JsonResult recuperarDatos(int IdCus)
        {

            SegCursoUsuarioLinksCLS oSegCursoUsuarioLinksCLS = new SegCursoUsuarioLinksCLS();
            using (var db = new DB_WebCIIPEntitiesERP())
            {
                SEG_CURSOS_USUARIOS_LINKS oSEG_CURSOS_USUARIOS_LINKS = db.SEG_CURSOS_USUARIOS_LINKS.Where(p => p.CUS_ID == IdCus).First();
                oSegCursoUsuarioLinksCLS.CUR_ID = oSEG_CURSOS_USUARIOS_LINKS.CUR_ID;
                oSegCursoUsuarioLinksCLS.USU_ID = oSEG_CURSOS_USUARIOS_LINKS.USU_ID;
                oSegCursoUsuarioLinksCLS.USU_LINK = oSEG_CURSOS_USUARIOS_LINKS.USU_LINK;
                oSegCursoUsuarioLinksCLS.USU_LINK_CORTO = oSEG_CURSOS_USUARIOS_LINKS.USU_LINK_CORTO;
                
            }
            return Json(oSegCursoUsuarioLinksCLS, JsonRequestBehavior.AllowGet);


        }



        public string GuardarNuevoControladorParcial(SegCursoUsuarioLinksCLS oSegCursoUsuarioLinksCLS, int accion)
        {

            int idCus = 0;
            int nregistradosEncontradosCur = 0;
            int nregistradosEncontradosUsu = 0;
            int nregistradosExistentes = 0;
            string rpta = "";

            string LinkDoc = WebConfigurationManager.AppSettings["LinkDocentes"];


            if (!ModelState.IsValid && accion == -1)
            {

                string valor;
                var query = (from state in ModelState.Values
                             from error in state.Errors
                             select error.ErrorMessage).ToList();

                rpta += "<ul class='list-group'>";
                foreach (var item in query)
                {
                    valor = item.Contains("Foto").ToString();

                    rpta += "<li class='list-group-item'>" + item + "</li>";

                }
                rpta += "</ul>";
            }
            else
            {
                if (oSegCursoUsuarioLinksCLS.CUR_ID == 0)
                {
                    rpta = "-1";
                }
                else if (oSegCursoUsuarioLinksCLS.USU_ID == 0)
                {
                    rpta = "-1";
                }
                else
                {
                    using (var db = new DB_WebCIIPEntitiesERP())
                    {
                        if (accion.Equals(-1))
                        {

                            //iniciamos concatenacion del link

                            nregistradosEncontradosCur = db.MAE_CURSOS.Where(x => x.CUR_ID.Equals(oSegCursoUsuarioLinksCLS.CUR_ID)).Count();

                            nregistradosEncontradosUsu = db.SEG_USUARIOS.Where(x => x.USU_ID.Equals(oSegCursoUsuarioLinksCLS.USU_ID)).Count();

                            nregistradosExistentes = db.SEG_CURSOS_USUARIOS_LINKS.Where(x => x.CUR_ID.Equals(oSegCursoUsuarioLinksCLS.CUR_ID) &&
                                                                                                        x.USU_ID.Equals(oSegCursoUsuarioLinksCLS.USU_ID)).Count();

                            if (nregistradosEncontradosCur == 0 && nregistradosEncontradosUsu == 0)
                            {
                                rpta = "-11";
                            }
                            else if (nregistradosExistentes !=0 ) {
                                rpta = "-2";
                            }
                            else
                            {

                                SEG_USUARIOS oSEG_USUARIOS = db.SEG_USUARIOS.Where(p => p.USU_ID.Equals(oSegCursoUsuarioLinksCLS.USU_ID)).First();
                                MAE_CURSOS oMAE_CURSOS = db.MAE_CURSOS.Where(q => q.CUR_ID.Equals(oSegCursoUsuarioLinksCLS.CUR_ID)).First();




                                SEG_CURSOS_USUARIOS_LINKS oSEG_CURSOS_USUARIOS_LINKS = new SEG_CURSOS_USUARIOS_LINKS();

WebCIIPMaestrosERP/Views/SegCursosUsuariosLinks/Index.cshtml
@using WebCIIPMaestrosERP.Models;
@model List<SegCursoUsuarioLinksCLS>

@{
    ViewBag.Title = "Index";
    List<SelectListItem> ListaCursos = (List<SelectListItem>)ViewBag.ListaCursos;
    List<SelectListItem> ListaUsuarios = (List<SelectListItem>)ViewBag.ListaUsuarios;

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>






    @using (Ajax.BeginForm("Filtro", "", new AjaxOptions
    {
        HttpMethod = "POST",
        UpdateTargetId = "divRol",
        InsertionMode = InsertionMode.Replace
    }, new { @id = "frmFiltro" }))
    {


        <div class="container">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-4">
                            <h2>Relacionar Cursos y Usuarios</h2>
                        </div>
                        <div class="col-sm-4">
                            <form class="navbar-form navbar-left ">
                                <div class="form-group">
                                    @Html.TextBox("nombreUsuario", null, new { @class = "form-control", @placeholder = "Buscar usuario" })
                                </div>

                            </form>
                        </div>

                        <div class="col-sm-4">
                            <a href="#myModalCurso" onclick="Agregar()" class="btn btn-success" data-toggle="modal"><i class="material-icons">&#xE147;</i> <span>Agregar</span></a>
                        </div>
                    </div>
                </div>

                <div id="divRol">





                    @Html.Partial("_Index", Model)




                </div>
            </div>
        </div>
    }




    <!-- Modal -->
    <div class="modal fade" id="myModalCurso" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Registrar</h4>
                </div>


                @using (Ajax.BeginForm("GuardarNuevoControladorParcial", "SegCursosUsuariosLinks", null, new AjaxOptions
                {
                    HttpMethod = "POST",
                    OnSuccess = "Guardar",
                    UpdateTargetId = "error"
                }))
                {

                    @Html.Hidden("accion") //Para  saber si esta guardando o actualizando, -1 = insertar, -2 actualuzar


                    <div class="modal-body">
                        <div class="form-group">

                            <div class="row">
                                <div class="form-group col-lg-6">
                                    @Html.LabelFor(p => Model[0].USU_NOMBRES)
                                    @Html.DropDownList("USU_ID", ListaUsuarios, new { @class = "form-control" })
                                </div>
                                <div class="form-group col-lg-6">
                                    @Html.LabelFor(p => Model[0].CUR_ID)
                                    @Html.DropDownList("CUR_ID", ListaCursos, new { @class = "form-control" })
                                </div>
                            </div>


                            <div class="row">

                                <div class="form-group col-lg-12">
                                    @Html.LabelFor(p => Model[0].USU_LINK_CORTO)
                                    @Html.TextBox("USU_LINK_CORTO", null, new { @class = "form-control" })
                                </div>


                            </div>





                        </div>
                    </div>






                    <div class="modal-footer">




                        <button type="button" id="btnClose" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>


                }
            </div>
            <div class="text-danger" id="error"></div>
        </div>
    </div>


    <!-- Modal Eliminar
    <div class="modal fade" id="ModalConfirmacion" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">

                    <div class="alert alert-danger" role="alert"><h5 class="modal-title" id="exampleModalLabel">¿Desea desactivar el registro?</h5></div>

                </div>

                <div style="padding:1em">
                    <button type="button" id="btnCerrarConfirmacion" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="button" onclick="ConfirmarActivarDescativar(2)" class="btn btn-danger">Aceptar</button>
                </div>
            </div>
        </div>
    </div>
        -->
    <!-- Delete Modal HTML -->
    <div id="ModalConfirmacion" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <form>
                    <div class="modal-header">
                        <h4 class="modal-title">¿Desea desactivar el registro?</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-body">
                        <p>Esta seguro que desea desactivar el curso?</p>
                        <p class="text-warning"><small>Esta accion puede deshacerse.</small></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" id="btnCerrarConfirmacion" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        <button type="button" onclick="ConfirmarActivarDescativar(2)" class="btn btn-danger">Aceptar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <!-- Modal Ver Link -->
    <div class="modal fade" id="ModalVerLink" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">

                    <div class="alert alert-success" role="alert"><h5 class="modal-title" id="ModalLabel">Ver Link</h5></div>

                    <textarea class="col-md-12" id="Link" cols="100" rows="10"></textarea>


                </div>

                <div style="padding:1em">
                    <button type="button" id="btnCerrarConfirmacion" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal Activar -->
    <div class="modal fade" id="ModalActivar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">

                    <div class="alert alert-success" role="alert"><h5 class="modal-title" id="exampleModalLabel">¿Desea activar el registro?</h5></div>

                </div>

                <div style="padding:1em">
                    <button type="button" id="btnCerrarConfirmacion" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="button" onclick="ConfirmarActivarDescativar(1)" class="btn btn-success">Aceptar</button>
                </div>
            </div>
        </div>
    </div>

    <script>



        var nombre = document.getElementById("nombreUsuario");
        nombre.onkeyup = function () {
            $("#frmFiltro").trigger("submit");
        }


        function limpiar() {
            var controles = document.getElementsByClassName("form-control");
            var ncontroles = controles.length;

            for (var i = 0; i < ncontroles; i++) {
                controles[i] = value = "";

            }


            document.getElementById("USU_ID").value = "";
            document.getElementById("CUR_ID").value = "";
            document.getElementById("USU_LINK_CORTO").value = "";


            document.getElementById("error").innerHTML = "";

        }

        function ConfirmarActivarDescativar(estado) {
            var id = document.getElementById("accion").value;
            $.get("SegCursosUsuariosLinks/ActivarDesactivar/?id=" + id + "&estado=" + estado, function (data) {

                if (data == 1) {
                    alert("Se ejecuto correctamente");
                    document.getElementById("btnCerrarConfirmacion").click();
                    $("#frmFiltro").trigger("submit");
                } else {
                    alert("Ocurrio un error");
                }

            })

        }

        function ActivarDesactivar(idCus) {
            document.getElementById("accion").value = idCus;
        }

        function Agregar() {
            limpiar();
            document.getElementById("accion").value = -1;



        }

        function Guardar(resultado) {
            if (resultado == 1) {

                document.getElementById("btnClose").click();
                $("#frmFiltro").trigger("submit");
                alert("Se guardo correctamente");
            } else if (resultado == -2) {
                toastr["info"]("¡El usuario y curso ya se encuentran registrados!", "Links");
            
            } else {
                alert("Ocurrio un error");
            }

        }

        function Editar(idCus) {
            limpiar();
            //document.getElementById("error").innerHTML = "";
            //document.getElementById("accion").value = idUsuario;
            document.getElementById("accion").value = idCus;

            $.get("SegCursosUsuariosLinks/recuperarDatos/?IdCus=" + idCus, function (data) {


                document.getElementById("CUR_ID").value = data.CUR_ID;
                document.getElementById("USU_ID").value = data.USU_ID;
                document.getElementById("USU_LINK_CORTO").value = data.USU_LINK_CORTO;


            })

        }

        function VerLink(idCus) {

            $.get("SegCursosUsuariosLinks/recuperarDatos/?IdCus=" + idCus, function (data) {

                document.getElementById('Link').innerHTML = data.USU_LINK;
            })
            
        }



    </script>



</body>
</html>

WebCIIPMaestrosERP/Views/SegCursosUsuariosLinks/VerLinks.cshtml
@using WebCIIPMaestrosERP.Models;
@model List<SegCursoUsuarioLinksCLS>


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>VerLinks</title>
</head>
<body>
    <div>
    </div>
</body>
</html>

WebCIIPMaestrosERP/Views/SegCursosUsuariosLinks/_Index.cshtml
@using WebCIIPMaestrosERP.Models;
@model List<SegCursoUsuarioLinksCLS>





<table class="table border-bottom table-hover table-striped">
    <thead>
        <tr>
            
            <th width="10%">@Html.LabelFor(p => Model[0].CUR_NOMBRE)</th>
            <th width="20%">@Html.LabelFor(p => Model[0].CUR_DESCRIPCION)</th>
            <th width="10%">@Html.LabelFor(p => Model[0].USU_NOMBRES)</th>
            <th width="20%">@Html.LabelFor(p => Model[0].USU_LINK_CORTO)</th>
            <th width="20%">OPERACIONES</th>

        </tr>
    <thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            
            <td>@item.CUR_NOMBRE</td>
            <td>@item.CUR_DESCRIPCION</td>
            <td>@item.USU_NOMBRES</td>
            <td>@item.USU_LINK_CORTO</td>
            <td>


                <a href="#myModalCurso" class="edit" onclick="Editar(@item.CUS_ID)" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
                <a href="#ModalVerLink" class="edit" onclick="VerLink(@item.CUS_ID)" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xe894;</i></a>
                <a href="#ModalConfirmacion" class="delete" onclick="ActivarDesactivar(@item.CUS_ID)" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Activar">&#xe003;</i></a>
                <a href="#ModalActivar" class="active" onclick="ActivarDesactivar(@item.CUS_ID)" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>

            </td>
        </tr>
        }
    </tbody>
</table>