WebCIIPMaestrosERP/Models/SEG_USUARIOS.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCIIPMaestrosERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEG_USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEG_USUARIOS()
        {
            this.SEG_USUARIOS_LINKS = new HashSet<SEG_USUARIOS_LINKS>();
            this.SEG_CURSOS_USUARIOS_LINKS = new HashSet<SEG_CURSOS_USUARIOS_LINKS>();
            this.MKT_DOCENTE_CURSO = new HashSet<MKT_DOCENTE_CURSO>();
        }
    
        public int USU_ID { get; set; }
        public string USU_NOMBRES { get; set; }
        public string USU_APELLIDO { get; set; }
        public string USU_EMAIL { get; set; }
        public string USU_DIRECCION { get; set; }
        public string USU_CELULAR { get; set; }
        public int ROL_ID { get; set; }
        public string USU_ACTIVO { get; set; }
        public string USU_ID_ENCRIPTADO { get; set; }
        public string USU_CONTRASENA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEG_USUARIOS_LINKS> SEG_USUARIOS_LINKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEG_CURSOS_USUARIOS_LINKS> SEG_CURSOS_USUARIOS_LINKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MKT_DOCENTE_CURSO> MKT_DOCENTE_CURSO { get; set; }
        public virtual MAE_ROLES MAE_ROLES { get; set; }
    }
}

WebCIIPMaestrosERP/Controllers/SegUsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Transactions;
using System.Text;
using System.Web;
using System.Web.Mvc;
using WebCIIPMaestrosERP.Models;
using WebCIIPMaestrosERP.Seguridad;

namespace WebCIIPMaestrosERP.Controllers
{
    [Acceder]
    public class SegUsuariosController : Controller
    {
        // GET: SegUsuarios
        public ActionResult Index(SegUsuariosCLS osegUsuariosCLS)
        {


            llenarRol();


            string nombreUsuario = osegUsuariosCLS.USU_NOMBRES;
            List<SegUsuariosCLS> ListaUsuarios = null;

            using (var db = new DB_WebCIIPEntitiesERP())
            {

                if (osegUsuariosCLS.USU_NOMBRES == null)
                {
                    ListaUsuarios = (from usuarios in db.SEG_USUARIOS
                                     join rol in db.MAE_ROLES
                                     on usuarios.ROL_ID equals rol.ROL_ID
                                     join tablas in db.MAE_TABLAS
                                     on usuarios.USU_ACTIVO equals tablas.ID.ToString()
                                     where tablas.COD_TABLA == "ACT"
                                     orderby usuarios.USU_ID

                                     select new SegUsuariosCLS

                                     {

                                         USU_ID = usuarios.USU_ID,
                                         USU_NOMBRES = usuarios.USU_NOMBRES,
                                         USU_APELLIDO = usuarios.USU_APELLIDO,
                                         USU_EMAIL = usuarios.USU_EMAIL,
                                         USU_DIRECCION = usuarios.USU_DIRECCION,
                                         USU_CELULAR = usuarios.USU_CELULAR,
                                         ROL_ID = (int)usuarios.ROL_ID,
                                         ROL_DESCRIPCION = rol.ROL_DESCRIPCION,
                                         USU_ACTIVO = tablas.DESCRIPCION,
                                         USU_ID_ENCRIPTADO = usuarios.USU_ID_ENCRIPTADO

                                     }).ToList();
                }
                else
                {
                    ListaUsuarios = (from usuarios in db.SEG_USUARIOS
                                     join rol in db.MAE_ROLES
                                     on usuarios.ROL_ID equals rol.ROL_ID
                                     join tablas in db.MAE_TABLAS
                                     on usuarios.USU_ACTIVO equals tablas.ID.ToString()
                                     where usuarios.USU_NOMBRES.Contains(nombreUsuario) &&
                                           tablas.COD_TABLA == "ACT"
                                     orderby usuarios.USU_ID

                                     select new SegUsuariosCLS

                                     {

                                         USU_ID = usuarios.USU_ID,
                                         USU_NOMBRES = usuarios.USU_NOMBRES,
                                         USU_APELLIDO = usuarios.USU_APELLIDO,
                                         USU_EMAIL = usuarios.USU_EMAIL,
                                         USU_DIRECCION = usuarios.USU_DIRECCION,
                                         USU_CELULAR = usuarios.USU_CELULAR,
                                         ROL_ID = (int)usuarios.ROL_ID,
                                         ROL_DESCRIPCION = rol.ROL_DESCRIPCION,
                                         USU_ACTIVO = tablas.DESCRIPCION,
                                         USU_ID_ENCRIPTADO = usuarios.USU_ID_ENCRIPTADO

                                     }).ToList();


                }
            }

            return View(ListaUsuarios);
        }

        public int ActivarDesactivar(int id, string estado)
        {
            int nregistrosAfectados = 0;
            try
            {
                using (var db = new DB_WebCIIPEntitiesERP())
                {
                    SEG_USUARIOS oSEG_USUARIOS = db.SEG_USUARIOS.Where(p => p.USU_ID == id).First();
                    oSEG_USUARIOS.USU_ACTIVO = estado;
                    nregistrosAfectados = db.SaveChanges();
                }

            }
            catch (Exception ex)
            {

                nregistrosAfectados = 0;
            }

            return nregistrosAfectados;
        }

        public ActionResult Filtro(string nombreUsuario)
        {

            List<SegUsuariosCLS> listaUsuarios = new List<SegUsuariosCLS>();
            using (var db = new DB_WebCIIPEntitiesERP())
            {
                if (nombreUsuario == null)
                    listaUsuarios = (from usuarios in db.SEG_USUARIOS
                                     join rol in db.MAE_ROLES
                                     on usuarios.ROL_ID equals rol.ROL_ID
                                     join tablas in db.MAE_TABLAS
                                     on usuarios.USU_ACTIVO equals tablas.ID.ToString()
                                     where tablas.COD_TABLA == "ACT"
                                     orderby usuarios.USU_ID

                                     select new SegUsuariosCLS

                                     {

                                         USU_ID = usuarios.USU_ID,
                                         USU_NOMBRES = usuarios.USU_NOMBRES,
                                         USU_APELLIDO = usuarios.USU_APELLIDO,
                                         USU_EMAIL = usuarios.USU_EMAIL,
                                         USU_DIRECCION = usuarios.USU_DIRECCION,
                                         USU_CELULAR = usuarios.USU_CELULAR,
                                         ROL_ID = (int)usuarios.ROL_ID,
                                         ROL_DESCRIPCION = rol.ROL_DESCRIPCION,
                                         USU_ACTIVO = tablas.DESCRIPCION,
                                         USU_ID_ENCRIPTADO = usuarios.USU_ID_ENCRIPTADO
                                     }).ToList();
                else
                    listaUsuarios = (from usuarios in db.SEG_USUARIOS
                                     join rol in db.MAE_ROLES
                                     on usuarios.ROL_ID equals rol.ROL_ID
                                     join tablas in db.MAE_TABLAS
                                     on usuarios.USU_ACTIVO equals tablas.ID.ToString()
                                     where (usuarios.USU_NOMBRES.Contains(nombreUsuario) ||
                                            usuarios.USU_APELLIDO .Contains(nombreUsuario)) &&
                                           tablas.COD_TABLA == "ACT"
                                     orderby usuarios.USU_ID


                                     select new SegUsuariosCLS

                                     {

                                         USU_ID = usuarios.USU_ID,
                                         USU_NOMBRES = usuarios.USU_NOMBRES,
                                         USU_APELLIDO = usuarios.USU_APELLIDO,
                                         USU_EMAIL = usuarios.USU_EMAIL,
                                         USU_DIRECCION = usuarios.USU_DIRECCION,
                                         USU_CELULAR = usuarios.USU_CELULAR,
                                         ROL_ID = (int)usuarios.ROL_ID,
                                         ROL_DESCRIPCION = rol.ROL_DESCRIPCION,
                                         USU_ACTIVO = tablas.DESCRIPCION,
                                         USU_ID_ENCRIPTADO = usuarios.USU_ID_ENCRIPTADO
                                     }).ToList();
            }
            return PartialView("_Index", listaUsuarios);
        }

        public JsonResult recuperarDatos(int IdUsuario) {

            SegUsuariosCLS oSegUsuariosCLS = new SegUsuariosCLS();
            using (var db = new DB_WebCIIPEntitiesERP())
            {
                SEG_USUARIOS oSEG_USUARIOS = db.SEG_USUARIOS.Where(p => p.USU_ID == IdUsuario).First();
                oSegUsuariosCLS.USU_NOMBRES = oSEG_USUARIOS.USU_NOMBRES;
                oSegUsuariosCLS.USU_APELLIDO = oSEG_USUARIOS.USU_APELLIDO;
                oSegUsuariosCLS.USU_CELULAR = oSEG_USUARIOS.USU_CELULAR;
                oSegUsuariosCLS.USU_EMAIL = oSEG_USUARIOS.USU_EMAIL;
                oSegUsuariosCLS.ROL_ID = oSEG_USUARIOS.ROL_ID;
                oSegUsuariosCLS.USU_CONTRASENA = oSEG_USUARIOS.USU_CONTRASENA;
                


            }
            return Json(oSegUsuariosCLS, JsonRequestBehavior.AllowGet);

            
        }

      

        private void llenarRol()
        {
            List<SelectListItem> Lista;
            using (var db = new DB_WebCIIPEntitiesERP())
            {

                Lista = (from roles in db.MAE_ROLES
                               select new SelectListItem
                               {
                                   Text = roles.ROL_DESCRIPCION,
                                   Value = roles.ROL_ID.ToString()

                               }).ToList();
                ViewBag.listaRol = Lista;
            }

        }

        public string GuardarNuevoControladorParcial(SegUsuariosCLS oSegUsuariosCLS, int accion)
        {

            decimal idUsuario = 0;
            string rpta = "";

            //valida que los campos sean poblados
            if (!ModelState.IsValid)
            {
                var query = (from state in ModelState.Values
                             from error in state.Errors
                             select error.ErrorMessage).ToList();
                rpta += "<ul class='list-group'>";
                foreach (var item in query)
                {
                    rpta += "<li class='list-group-item'>" + item + "</li>";
                }
                rpta += "</ul>";

            }
            else {

              

WebCIIPMaestrosERP/Views/SegUsuarios/Index.cshtml
@using WebCIIPMaestrosERP;
@model List<WebCIIPMaestrosERP.Models.SegUsuariosCLS>

@{
    List<SelectListItem> listaRol = (List<SelectListItem>)ViewBag.listaRol;
}

@using (Ajax.BeginForm("Filtro", "", new AjaxOptions
{
    HttpMethod = "POST",
    UpdateTargetId = "divRol",
    InsertionMode = InsertionMode.Replace
}, new { @id = "frmFiltro" }))
{


    <div class="container">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-4">
                        <h2>Administrar <b>Usuarios</b></h2>
                    </div>
                    <div class="col-sm-4">
                        <form class="navbar-form navbar-left ">
                            <div class="form-group">
                                @*<input id="optPage" type="hidden" name="page"/>*@
                                @Html.Hidden("page", null, new { @id = "optPage" })
                                @Html.TextBox("nombreUsuario", null, new { @class = "form-control", @placeholder = "Buscar curso" })
                            </div>
                        </form>
                    </div>

                    <div class="col-sm-4">
                        <a href="#myModalUsuario" onclick="Agregar()" class="btn btn-success" data-toggle="modal"><i class="material-icons">&#xE147;</i> <span>Agregar</span></a>
                        <!--<a href="#Any" onclick="SP_Execute()" class="btn btn-info"><i class="glyphicon glyphicon-play"></i> <span>Proccess</span></a>-->
                    </div>
                </div>
            </div>

            <div id="divRol">





                @Html.Partial("_Index", Model)




            </div>
        </div>
    </div>
}



<!-- Modal -->
<div class="modal fade" id="myModalUsuario" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Nuevo Usuario</h4>
            </div>


            @using (Ajax.BeginForm("GuardarNuevoControladorParcial", "SegUsuarios", null, new AjaxOptions
            {
                HttpMethod = "POST",
                OnSuccess = "Guardar",
                UpdateTargetId = "error"
            }))
            {

                @Html.Hidden("accion") //Para  saber si esta guardando o actualizando, -1 = insertar, -2 actualuzar


                <table>
                    <tr>
                        <td>
                            <div class="modal-body">
                                @Html.LabelFor(p => Model[0].USU_NOMBRES)
                                @Html.TextBox("USU_NOMBRES", null, new { @class = "form-control" })

                            </div>
                        </td>
                        <td>
                            <div class="modal-body">
                                @Html.LabelFor(p => Model[0].USU_APELLIDO)
                                @Html.TextBox("USU_APELLIDO", null, new { @class = "form-control" })

                            </div>
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <div class="modal-body">
                                @Html.LabelFor(p => Model[0].USU_EMAIL)
                                @Html.TextBox("USU_EMAIL", null, new { @class = "form-control" })

                            </div>
                        </td>
                        <td>
                            <div class="modal-body">
                                @Html.LabelFor(p => Model[0].USU_CELULAR)
                                @Html.TextBox("USU_CELULAR", null, new { @class = "form-control" })

                            </div>
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <div class="modal-body">
                                @Html.LabelFor(p => Model[0].ROL_ID)
                                @Html.DropDownList("ROL_ID", listaRol, new { @class = "form-control" })
                            </div>
                        </td>
                        <td>
                            <div class="modal-body">
                                @Html.LabelFor(p => Model[0].USU_CONTRASENA)
                                @Html.Password("USU_CONTRASENA", null, new { @class = "form-control", @placeholder = "Contrasena" })
                            </div>
                        </td>
                    </tr>

                </table>

                <div class="modal-footer">
                    <button type="button" id="btnClose" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>


            }
        </div>
        <div class="text-danger" id="error"></div>
    </div>
</div>


<!-- Modal Eliminar -->
<div class="modal fade" id="ModalConfirmacion" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">

                <div class="alert alert-danger" role="alert"><h5 class="modal-title" id="exampleModalLabel">¿Desea desactivar el registro?</h5></div>

            </div>

            <div style="padding:1em">
                <button type="button" id="btnCerrarConfirmacion" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" onclick="ConfirmarActivarDescativar(2)" class="btn btn-danger">Aceptar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Activar -->
<div class="modal fade" id="ModalActivar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">

                <div class="alert alert-success" role="alert"><h5 class="modal-title" id="exampleModalLabel">¿Desea activar el registro?</h5></div>

            </div>

            <div style="padding:1em">
                <button type="button" id="btnCerrarConfirmacion" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" onclick="ConfirmarActivarDescativar(1)" class="btn btn-success">Aceptar</button>
            </div>
        </div>
    </div>
</div>


<script>

    var nombre = document.getElementById("nombreUsuario");
    nombre.onkeyup = function () {
        $("#frmFiltro").trigger("submit");
    }

    function ConfirmarActivarDescativar(estado) {
        var id = document.getElementById("accion").value;
        $.get("SegUsuarios/ActivarDesactivar/?id=" + id + "&estado=" + estado, function (data) {

            if (data == 1) {
                alert("Se ejecuto correctamente");
                document.getElementById("btnCerrarConfirmacion").click();
                $("#frmFiltro").trigger("submit");
            } else {
                alert("Ocurrio un error");
            }

        })

    }


    function ActivarDesactivar(idUsuario) {
        document.getElementById("accion").value = idUsuario;
    }


    function limpiar() {
        var controles = document.getElementsByClassName("form-control");
        var ncontroles = controles.length;

        for (var i = 0; i < ncontroles; i++) {
            controles[i] = value = "";

        }

        document.getElementById("USU_NOMBRES").value = "";
        document.getElementById("USU_APELLIDO").value = "";
        document.getElementById("USU_CELULAR").value = "";
        document.getElementById("USU_EMAIL").value = "";
        document.getElementById("ROL_ID").value = "";
        document.getElementById("USU_CONTRASENA").value = "";


        document.getElementById("error").innerHTML = "";

    }

    function Agregar() {
        limpiar();
        document.getElementById("accion").value = -1;

    }

    function Guardar(resultado) {
        if (resultado == 1) {


            alert("Se guardo correctamente");
            $("#frmFiltro").trigger("submit");
            document.getElementById("btnClose").click();

        } else {
            alert("Ocurrio un error");
        }
        

    }

    function Editar(idUsuario) {
        limpiar();
        //document.getElementById("error").innerHTML = "";
        //document.getElementById("accion").value = idUsuario;
        document.getElementById("accion").value = idUsuario;



        $.get("SegUsuarios/recuperarDatos/?IdUsuario=" + idUsuario, function (data) {


            document.getElementById("USU_NOMBRES").value = data.USU_NOMBRES;
            document.getElementById("USU_APELLIDO").value = data.USU_APELLIDO;
            document.getElementById("USU_CELULAR").value = data.USU_CELULAR;
            document.getElementById("USU_EMAIL").value = data.USU_EMAIL;
            document.getElementById("ROL_ID").value = data.ROL_ID;
            document.getElementById("USU_CONTRASENA").value = data.USU_CONTRASENA;


        })

    }



</script>

WebCIIPMaestrosERP/Views/SegUsuarios/_Index.cshtml
@using WebCIIPMaestrosERP;
@model List<WebCIIPMaestrosERP.Models.SegUsuariosCLS>



    <table class="table border-bottom table-hover">
        <thead>
            <tr>
                <td width="5%">@Html.LabelFor(p => Model[0].USU_ID)</td>
                <td width="10%">@Html.LabelFor(p => Model[0].USU_NOMBRES)</td>
                <td width="10%">@Html.LabelFor(p => Model[0].USU_APELLIDO)</td>
                <td width="15%">@Html.LabelFor(p => Model[0].ROL_DESCRIPCION)</td>
                <td width="15%">@Html.LabelFor(p => Model[0].USU_CELULAR)</td>
                <td width="10%">@Html.LabelFor(p => Model[0].USU_ACTIVO)</td>
                <td width="10%">Operaciones</td>

            </tr>
        <thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>@item.USU_ID</td>
                <td>@item.USU_NOMBRES</td>
                <td>@item.USU_APELLIDO</td>
                <td>@item.ROL_DESCRIPCION</td>
                <td>@item.USU_CELULAR</td>
                <td>@item.USU_ACTIVO</td>
                

                <td>

                    <a href="#myModalUsuario" class="edit" onclick="Editar(@item.USU_ID)" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
                    <a href="#ModalConfirmacion" class="delete" onclick="ActivarDesactivar(@item.USU_ID)" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Activar">&#xE872;</i></a>
                    <a href="#ModalActivar" class="active" onclick="ActivarDesactivar(@item.USU_ID)" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xe003;</i></a>


                </td>
            </tr>
            }
        </tbody>
    </table>


<script>

    var nombre = document.getElementById("USU_NOMBRE");
    nombre.onkeyup = function () {
        var frmUsuarios = document.getElementById("frmFiltro");
        frmUsuarios.submit();
    }


</script>